@startuml

:Користувач: as user

user<...(Завантажити документ)

(Завантажити документ)<...(Указати шлях)

(Завантажити документ)<...(Указати формат)

(Завантажити документ)<...(Прикріпити 'ключі' \nдо документа)

@endum
