@startuml

(Знайти документ)<...(Пошук по даті)

(Знайти документ)<...(Пошук по персональній \nінформації)

(Знайти документ)<...(Пошук по 'ключеві')

(Знайти документ)<...(Пошук по розміру)

(Знайти документ)<...(Пошук по назві)

@endum
