@startuml

:Користувач: as user

user<...(Мої документи)

(Мої документи)<...(Перегляд \nдокументу)

(Мої документи)<...(Зміна \nдокументу)
(Зміна \nдокументу)<...(Надання доступу)
(Зміна \nдокументу)<...(Присвоєння 'ключів')
(Зміна \nдокументу)<...(Редагування)

(Мої документи)<...(Поділитись \nдокументом)
(Поділитись \nдокументом)<...(Встановлення прав)
(Поділитись \nдокументом)<...(Вказати \nодержувача)

(Мої документи)<...(Створити дублікат \nдокументу)
(Створити дублікат \nдокументу)<...(Вказати назву)
(Створити дублікат \nдокументу)<...(Вказати формат)

(Мої документи)<...(Скачати \nдокумент)
(Скачати \nдокумент)<...(Вказати формат)
(Скачати \nдокумент)<...(Вказати шлях)

(Мої документи)<...(Видалити \nдокумент)

@endum
