@startuml

(Мої документи)<...(Перегляд)

(Мої документи)<...(Зміна \nдокументу)
(Зміна \nдокументу)<...(Надання доступу)
(Зміна \nдокументу)<...(Присвоєння 'ключів')
(Зміна \nдокументу)<...(Редагування)

(Мої документи)<...(Поділитись \nдокументом)
(Поділитись \nдокументом)<...(Встановлення прав)
(Поділитись \nдокументом)<...(Вказати \nодержувача)

(Мої документи)<...(Створити дублікат \nдокументу)
(Створити дублікат \nдокументу)<...(Указати назву)
(Створити дублікат \nдокументу)<...(Указати формат)

(Мої документи)<...(Скачати \nдокумент)
(Скачати \nдокумент)<...(Указати формат)
(Скачати \nдокумент)<...(Указати шлях)

(Мої документи)<...(Видалити \nдокумент)

@endum
