@startuml

:Користувач в \nособистому кабінеті: as user

user--->(Налаштування)
user--->(Історія)
user--->(Мої документи)
user--->(Завантажити документ)
user--->(Знайти документ)
user--->(Редагування/Скачування/\nВидалення документа)

(Редагування/Скачування/\nВидалення документа)<...(Інший користувач \nнадав конкретні \nправа )

@endum
