@startuml

:Користувач в \nособистому кабінеті: as user

user--->(Перейти в \nналаштування)
user--->(Показати історію)
user--->(Перейти в \nмої документи)
user--->(Завантажити документ)
user--->(Знайти документ)
user--->(Редагування/Скачування/\nВидалення документа)

(Редагування/Скачування/\nВидалення документа)<...(Інший користувач \nнадав конкретні \nправа )

@endum
