@startuml

(Налаштування)<...(Зміна теми)
(Налаштування)<...(Встановлення новин)
(Налаштування)<...(Автоматичне продовження \nз моменту останнього \nзакриття програми)
(Налаштування)<...(Зміна тексту, \nшрифта)
(Налаштування)<...(Зміна логіна, \nпароля)
(Налаштування)<...(Зміна профіля)
(Налаштування)<...(Зміна аккаунта)

(Зміна теми)<...(Вибір існуючої)
(Зміна теми)<...(Створення нової)

(Встановлення новин)<...(З'ясування інтересів)
(Зміна логіна, \nпароля)<...(Ввод старого логіна \nта пароля)
(Ввод старого логіна \nта пароля)<...(Ввод нового логіна \nабо пароля)

(Зміна профіля)<...(Зміна головної \nфотографії)
(Зміна головної \nфотографії)<...(Видалення)
(Зміна головної \nфотографії)<...(Завантаження)
(Зміна головної \nфотографії)<...(Зміна)

(Зміна профіля)<...(Зміна опису)
(Зміна опису)<...(Видалення)
(Зміна опису)<...(Зміна)

(Зміна аккаунта)<...(Відкритий)
(Зміна аккаунта)<...(Закритий)
@endum
