@startuml
:Незареєстрований користувач: as user1
:Зареєстрований користувач: as user2


user1--->(Реєстрація)
user1--->(Інформація про \nпошукову систему)
user1--->(Перегляд \nдокумента)

user2--->(Інформація про \nпошукову систему)
user2--->(Перегляд \nдокумента)
user2--->(Проблеми з \nвходом)
user2--->(Вхід в \nособистий кабінет)

(Перегляд \nдокумента)<...(Інший користувач \nподілився своїм \nдокументом)

(Вхід в \nособистий кабінет)<...(Введення \nпароля)
(Вхід в \nособистий кабінет)<...(Введення \nлогіна)

(Проблеми з \nвходом)<...(Укажіть пошту)
(Проблеми з \nвходом)<...(Забув пошту)
(Забув пошту)<...(Зв'язатись з помічником)
@endum
