@startuml

:Користувач: as user
:Незареєстрований користувач: as user1
:Зареєстрований користувач: as user2

user--->user1
user--->user2
user--->(Перегляд \nдокумента)
user--->(Інформація про \nпошукову систему)

user1--->(Реєстрація)

user2--->(Проблеми з \nвходом)
user2--->(Вхід в \nособистий кабінет)

(Перегляд \nдокумента)<...(Інший користувач \nподілився своїм \nдокументом)

(Вхід в \nособистий кабінет)<...(Введення \nпароля)
(Вхід в \nособистий кабінет)<...(Введення \nлогіна)

(Проблеми з \nвходом)<...(Укажіть пошту)
(Проблеми з \nвходом)<...(Забув пошту)

(Забув пошту)<...(Зв'язатись з помічником)

@endum
